Repository Spazzy757/paul, pull requests merged in 2020-10, with the labels that each got.

#15 Feature add CI/CD and Update Readme
  .github/workflows/tests.yaml
  README.md
Labels: enhancement

#23 Changed name of action file so it can be picked up
  .github/workflows/main.yaml
Labels: bug

#22 Enabled the Github Auth for Webhooks
  pkg/github/webhooks.go
  pkg/router/router.go
Labels: enhancement

#14 Adds The Command /dog
  PAUL.yaml
  mocks/cat-command.json
  mocks/dog-command.json
  pkg/animals/cats.go
  pkg/animals/cats_test.go
  pkg/animals/dogs.go
  pkg/animals/dogs_test.go
  pkg/animals/helpers.go
  pkg/animals/helpers_test.go
  pkg/github/issue.go
  pkg/github/issue_test.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
  pkg/types/types.go
  pkg/types/types_test.go
Labels: enhancement

#25 Fix Golint warning Issue
  pkg/animals/cats.go
  pkg/animals/dogs.go
  pkg/animals/helpers.go
  pkg/github/pullrequests.go
  pkg/github/webhooks.go
  pkg/helpers/helpers.go
  pkg/router/router.go
  pkg/types/types.go
Labels: bug, hacktoberfest-accepted

#28 Feature increase testing
  go.sum
  mocks/installation.json
  pkg/animals/animals.go
  pkg/animals/animals_test.go
  pkg/animals/cats_test.go
  pkg/animals/dogs.go
  pkg/animals/dogs_test.go
  pkg/github/client.go
  pkg/github/client_test.go
  pkg/github/issue.go
  pkg/github/issue_test.go
  pkg/github/pullrequests.go
  pkg/github/webhooks_test.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
  pkg/types/types_test.go
Labels: bug

#29 Added default branch functionality
  pkg/github/client.go
  pkg/github/client_test.go
  pkg/github/issue.go
  pkg/github/pullrequests.go
Labels: enhancement

#30 Updated README.md
  README.md
Labels: documentation

#31 Added functionality to label issues
  PAUL.yaml
  pkg/github/issue.go
  pkg/github/issue_test.go
  pkg/types/types.go
  pkg/types/types_test.go
Labels: enhancement

#32 Feature branch destroyer
  PAUL.yaml
  mocks/merged-pr.json
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/github/client.go
  pkg/github/client_test.go
  pkg/github/issue.go
  pkg/github/issue_test.go
  pkg/github/pullrequests.go
  pkg/github/pullrequests_test.go
  pkg/github/webhooks.go
  pkg/github/webhooks_test.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
  pkg/router/router.go
  pkg/test/client.go
  pkg/test/client_test.go
  pkg/types/types.go
  pkg/types/types_test.go
Labels: enhancement

#37 Added Pull Request Limiter
  PAUL.yaml
  README.md
  pkg/github/pullrequests.go
  pkg/github/pullrequests_test.go
  pkg/github/webhooks_test.go
  pkg/test/client.go
  pkg/types/types.go
  pkg/types/types_test.go
Labels: enhancement

#39 Fixed branch destroyer
  pkg/github/pullrequests.go
  pkg/github/pullrequests_test.go
Labels: bug

#40 Updated documentation
  README.md
Labels: documentation

#41 Added the merge command
  README.md
  mocks/merge-command.json
  pkg/github/issue.go
  pkg/github/issue_test.go
  pkg/github/pullrequests.go
  pkg/github/pullrequests_test.go
Labels: enhancement

#42 Clean up complexity of the Issue Comment Handler
  pkg/github/issue.go
  pkg/github/issue_test.go
Labels: enhancement

#43 Go linter fix
  pkg/animals/animals.go
  pkg/router/router.go
  pkg/router/router_test.go
  pkg/test/client.go
Labels: bug

#44 Fixed more go linting errors
  pkg/config/config.go
  pkg/github/issue.go
  pkg/github/issue_test.go
  pkg/types/types.go
Labels: bug

#46 Update README.md
  README.md
Labels: documentation

#47 Added Empty Description Check
  PAUL.yaml
  README.md
  mocks/empty-description-pr.json
  pkg/github/pullrequests.go
  pkg/github/pullrequests_test.go
  pkg/types/types.go
  pkg/types/types_test.go
Labels: enhancement

#48 Disable Pushing to Codacy for Forks
  .github/workflows/main.yml
Labels: bug
